stages:
  - build
  - deploy

before_script:
  - apt-get install -y ruby-dev
  - gem install dpl

image: node

build-job:
  stage: build
  script:
  - npm install
  artifacts:
    paths:
      - node_modules
      - package-lock.json

deploy-job:
  stage: deploy
  script:
    - node index.js > /dev/null 2>&1 &
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY